eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone:http://localhost:8761/eureka

server:
  port: 8090
spring:
  application:
    name: students
  config:
    import: optional:configserver:http://localhost:8888
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3360/students
    username: root
    password: admin
  jpa:
    hibernate:
      ddl-auto: update
    database: mysql
    database-platform: org.hibernate.dialect.MysqlDialect
