server:
  port: 8222
eureka:
  client:
    register-with-eureka: false
spring:
  application:
    name: gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: students
          uri: http://localhost:9005
          predicates:
            - Path= /api/v1/student/**
        - id: schools
          uri: http://localhost:9006
          predicates:
            - Path= /api/v1/school/**

