
eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

server:
  port: 8070
spring:
  application:
    name: schools
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/schools
    username: root
    password: admin
  jpa:
    hibernate.ddl-auto: create
    generate-ddl: true
    show-sql: true
application:
  config:
    students-url: http://localhost:8090/api/v1/student