eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:8762/eureka/

server:
  port: 9005
spring:
  application:
    name: students
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/students
    username: root
    password: admin
  jpa:
    hibernate.ddl-auto: create
    generate-ddl: true
    show-sql: true
